BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "classes" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"type"	INTEGER,
	"base"	TEXT,
  "final" INTEGER,
	FOREIGN KEY("type") REFERENCES "types"("id")
);
COMMIT;
