BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "enumerators" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"enum_id"	INTEGER,
	FOREIGN KEY("enum_id") REFERENCES "enums"("id")
);
COMMIT;
