BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "enums" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"name"	TEXT NOT NULL,
	"enum_class"	INTEGER DEFAULT 0,
	"type"	INTEGER,
	FOREIGN KEY("type") REFERENCES "types"("id")
);
COMMIT;
