BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "metadata" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"entity_id"	INTEGER NOT NULL,
	"name"	TEXT NOT NULL,
	"value"	TEXT,
	FOREIGN KEY("entity_id") REFERENCES "entities"("id")
);
COMMIT;
