// Copyright (C) 2020 Vincent Chambrin
// This file is part of the 'gonk' project
// For conditions of distribution and use, see copyright notice in LICENSE

// Warning: This file was generated by metagonk, all modifications will be lost. //

#include "bytearray.h"

#include "gonk/common/binding/class.h"
#include "gonk/common/binding/namespace.h"
#include "gonk/common/enums.h"

#include <script/classbuilder.h>
#include <script/enumbuilder.h>

#include "qt-core/bytearray.h"
#include "qt-core/string.h"

namespace
{
script::Value bytearray_string_ctor(script::FunctionCall* c)
{
  c->thisObject().init<QByteArray>(script::get<std::string>(c->arg(1)).c_str());
  return c->thisObject();
}
}

#if METAGONK_SOURCE
{% assign bytearray_class = project | get_symbol: 'Qt.Core', 'QByteArray'%}
{% include generate_class with class = bytearray_class and recursive = true %}
{% assign current_class = project | get_symbol: 'Qt.Core', 'QByteRef'%}
{% include generate_class with class = current_class and recursive = true %}
#else

static void register_byte_array__base64_option(script::Class& parent)
{
  using namespace script;
  
  Enum base64_option = parent.newEnum("Base64Option").setId(script::Type::make<QByteArray::Base64Option>().data()).get();

  base64_option.addValue("Base64Encoding", QByteArray::Base64Option::Base64Encoding);
  base64_option.addValue("Base64UrlEncoding", QByteArray::Base64Option::Base64UrlEncoding);
  base64_option.addValue("KeepTrailingEquals", QByteArray::Base64Option::KeepTrailingEquals);
  base64_option.addValue("OmitTrailingEquals", QByteArray::Base64Option::OmitTrailingEquals);
}
namespace 
{
QByteArray bytearray_toLower(const QByteArray& self)
{
  return self.toLower();
}
QByteArray bytearray_toUpper(const QByteArray& self)
{
  return self.toUpper();
}
QByteArray bytearray_trimmed(const QByteArray& self)
{
  return self.trimmed();
}
QByteArray bytearray_simplified(const QByteArray& self)
{
  return self.simplified();
}
}

static void register_byte_array(script::Namespace& parent)
{
  using namespace script;
  
  Class byte_array = parent.newClass("QByteArray").setId(script::Type::make<QByteArray>().data())
    .get();

  Class& c = byte_array;
  
  register_byte_array__base64_option(c);
        
  // QByteArray::DataPtr& data_ptr();
  /// TODO: QByteArray::DataPtr& data_ptr();
  // QByteArray();
  gonk::bind::default_constructor<QByteArray>(c).create();
  // QByteArray(const char*, int);
  /// TODO: QByteArray(const char*, int);
  // QByteArray(int, char);
  gonk::bind::constructor<QByteArray, int, char>(c).create();
  // QByteArray(int, Qt::Initialization);
  /// TODO: QByteArray(int, Qt::Initialization);
  // QByteArray(const std::string&);
  gonk::bind::custom_constructor<QByteArray, const std::string&>(c, &bytearray_string_ctor).create();
  // QByteArray(const QByteArray&);
  gonk::bind::constructor<QByteArray, const QByteArray&>(c).create();
  // ~QByteArray();
  gonk::bind::destructor<QByteArray>(c).create();
  // QByteArray& operator=(const QByteArray&);
  gonk::bind::memop_assign<QByteArray, const QByteArray&>(c);
  // QByteArray& operator=(const char*);
  /// TODO: QByteArray& operator=(const char*);
  // QByteArray(QByteArray&&);
  gonk::bind::constructor<QByteArray, QByteArray&&>(c).create();
  // QByteArray& operator=(QByteArray&&);
  gonk::bind::memop_assign<QByteArray, QByteArray&&>(c);
  // void swap(QByteArray&);
  gonk::bind::void_member_function<QByteArray, QByteArray&, &QByteArray::swap>(c, "swap").create();
  // int size() const;
  gonk::bind::member_function<QByteArray, int, &QByteArray::size>(c, "size").create();
  // bool isEmpty() const;
  gonk::bind::member_function<QByteArray, bool, &QByteArray::isEmpty>(c, "isEmpty").create();
  // void resize(int);
  gonk::bind::void_member_function<QByteArray, int, &QByteArray::resize>(c, "resize").create();
  // QByteArray& fill(char, int);
  gonk::bind::member_function<QByteArray, QByteArray&, char, int, &QByteArray::fill>(c, "fill").create();
  // int capacity() const;
  gonk::bind::member_function<QByteArray, int, &QByteArray::capacity>(c, "capacity").create();
  // void reserve(int);
  gonk::bind::void_member_function<QByteArray, int, &QByteArray::reserve>(c, "reserve").create();
  // void squeeze();
  gonk::bind::void_member_function<QByteArray, &QByteArray::squeeze>(c, "squeeze").create();
  // char* data();
  /// TODO: char* data();
  // const char* data() const;
  /// TODO: const char* data() const;
  // const char* constData() const;
  /// TODO: const char* constData() const;
  // void detach();
  gonk::bind::void_member_function<QByteArray, &QByteArray::detach>(c, "detach").create();
  // bool isDetached() const;
  gonk::bind::member_function<QByteArray, bool, &QByteArray::isDetached>(c, "isDetached").create();
  // bool isSharedWith(const QByteArray&) const;
  gonk::bind::member_function<QByteArray, bool, const QByteArray&, &QByteArray::isSharedWith>(c, "isSharedWith").create();
  // void clear();
  gonk::bind::void_member_function<QByteArray, &QByteArray::clear>(c, "clear").create();
  // char at(int) const;
  gonk::bind::member_function<QByteArray, char, int, &QByteArray::at>(c, "at").create();
  // char operator[](int) const;
  gonk::bind::memop_const_subscript<QByteArray, char, int>(c);
  // char operator[](uint) const;
  /// TODO: char operator[](uint) const;
  // QByteRef operator[](int);
  gonk::bind::memop_subscript<QByteArray, QByteRef, int>(c);
  // QByteRef operator[](uint);
  /// TODO: QByteRef operator[](uint);
  // char front() const;
  gonk::bind::member_function<QByteArray, char, &QByteArray::front>(c, "front").create();
  // QByteRef front();
  gonk::bind::member_function<QByteArray, QByteRef, &QByteArray::front>(c, "front").create();
  // char back() const;
  gonk::bind::member_function<QByteArray, char, &QByteArray::back>(c, "back").create();
  // QByteRef back();
  gonk::bind::member_function<QByteArray, QByteRef, &QByteArray::back>(c, "back").create();
  // int indexOf(char, int) const;
  gonk::bind::member_function<QByteArray, int, char, int, &QByteArray::indexOf>(c, "indexOf").create();
  // int indexOf(const char*, int) const;
  /// TODO: int indexOf(const char*, int) const;
  // int indexOf(const QByteArray&, int) const;
  gonk::bind::member_function<QByteArray, int, const QByteArray&, int, &QByteArray::indexOf>(c, "indexOf").create();
  // int lastIndexOf(char, int) const;
  gonk::bind::member_function<QByteArray, int, char, int, &QByteArray::lastIndexOf>(c, "lastIndexOf").create();
  // int lastIndexOf(const char*, int) const;
  /// TODO: int lastIndexOf(const char*, int) const;
  // int lastIndexOf(const QByteArray&, int) const;
  gonk::bind::member_function<QByteArray, int, const QByteArray&, int, &QByteArray::lastIndexOf>(c, "lastIndexOf").create();
  // bool contains(char) const;
  gonk::bind::member_function<QByteArray, bool, char, &QByteArray::contains>(c, "contains").create();
  // bool contains(const char*) const;
  /// TODO: bool contains(const char*) const;
  // bool contains(const QByteArray&) const;
  gonk::bind::member_function<QByteArray, bool, const QByteArray&, &QByteArray::contains>(c, "contains").create();
  // int count(char) const;
  gonk::bind::member_function<QByteArray, int, char, &QByteArray::count>(c, "count").create();
  // int count(const char*) const;
  /// TODO: int count(const char*) const;
  // int count(const QByteArray&) const;
  gonk::bind::member_function<QByteArray, int, const QByteArray&, &QByteArray::count>(c, "count").create();
  // QByteArray left(int) const;
  gonk::bind::member_function<QByteArray, QByteArray, int, &QByteArray::left>(c, "left").create();
  // QByteArray right(int) const;
  gonk::bind::member_function<QByteArray, QByteArray, int, &QByteArray::right>(c, "right").create();
  // QByteArray mid(int, int) const;
  gonk::bind::member_function<QByteArray, QByteArray, int, int, &QByteArray::mid>(c, "mid").create();
  // QByteArray chopped(int) const;
  gonk::bind::member_function<QByteArray, QByteArray, int, &QByteArray::chopped>(c, "chopped").create();
  // bool startsWith(const QByteArray&) const;
  gonk::bind::member_function<QByteArray, bool, const QByteArray&, &QByteArray::startsWith>(c, "startsWith").create();
  // bool startsWith(char) const;
  gonk::bind::member_function<QByteArray, bool, char, &QByteArray::startsWith>(c, "startsWith").create();
  // bool startsWith(const char*) const;
  /// TODO: bool startsWith(const char*) const;
  // bool endsWith(const QByteArray&) const;
  gonk::bind::member_function<QByteArray, bool, const QByteArray&, &QByteArray::endsWith>(c, "endsWith").create();
  // bool endsWith(char) const;
  gonk::bind::member_function<QByteArray, bool, char, &QByteArray::endsWith>(c, "endsWith").create();
  // bool endsWith(const char*) const;
  /// TODO: bool endsWith(const char*) const;
  // void truncate(int);
  gonk::bind::void_member_function<QByteArray, int, &QByteArray::truncate>(c, "truncate").create();
  // void chop(int);
  gonk::bind::void_member_function<QByteArray, int, &QByteArray::chop>(c, "chop").create();
  // QByteArray toLower() const;
  gonk::bind::fn_as_memfn<QByteArray, QByteArray, &bytearray_toLower>(c, "toLower").create();
  // QByteArray toUpper() const;
  gonk::bind::fn_as_memfn<QByteArray, QByteArray, &bytearray_toUpper>(c, "toUpper").create();
  // QByteArray trimmed() const;
  gonk::bind::fn_as_memfn<QByteArray, QByteArray, &bytearray_trimmed>(c, "trimmed").create();
  // QByteArray simplified() const;
  gonk::bind::fn_as_memfn<QByteArray, QByteArray, &bytearray_simplified>(c, "simplified").create();
  // QByteArray leftJustified(int, char, bool) const;
  gonk::bind::member_function<QByteArray, QByteArray, int, char, bool, &QByteArray::leftJustified>(c, "leftJustified").create();
  // QByteArray rightJustified(int, char, bool) const;
  gonk::bind::member_function<QByteArray, QByteArray, int, char, bool, &QByteArray::rightJustified>(c, "rightJustified").create();
  // QByteArray& prepend(char);
  gonk::bind::member_function<QByteArray, QByteArray&, char, &QByteArray::prepend>(c, "prepend").create();
  // QByteArray& prepend(int, char);
  gonk::bind::member_function<QByteArray, QByteArray&, int, char, &QByteArray::prepend>(c, "prepend").create();
  // QByteArray& prepend(const char*);
  /// TODO: QByteArray& prepend(const char*);
  // QByteArray& prepend(const char*, int);
  /// TODO: QByteArray& prepend(const char*, int);
  // QByteArray& prepend(const QByteArray&);
  gonk::bind::member_function<QByteArray, QByteArray&, const QByteArray&, &QByteArray::prepend>(c, "prepend").create();
  // QByteArray& append(char);
  gonk::bind::member_function<QByteArray, QByteArray&, char, &QByteArray::append>(c, "append").create();
  // QByteArray& append(int, char);
  gonk::bind::member_function<QByteArray, QByteArray&, int, char, &QByteArray::append>(c, "append").create();
  // QByteArray& append(const char*);
  /// TODO: QByteArray& append(const char*);
  // QByteArray& append(const char*, int);
  /// TODO: QByteArray& append(const char*, int);
  // QByteArray& append(const QByteArray&);
  gonk::bind::member_function<QByteArray, QByteArray&, const QByteArray&, &QByteArray::append>(c, "append").create();
  // QByteArray& insert(int, char);
  gonk::bind::member_function<QByteArray, QByteArray&, int, char, &QByteArray::insert>(c, "insert").create();
  // QByteArray& insert(int, int, char);
  gonk::bind::member_function<QByteArray, QByteArray&, int, int, char, &QByteArray::insert>(c, "insert").create();
  // QByteArray& insert(int, const char*);
  /// TODO: QByteArray& insert(int, const char*);
  // QByteArray& insert(int, const char*, int);
  /// TODO: QByteArray& insert(int, const char*, int);
  // QByteArray& insert(int, const QByteArray&);
  gonk::bind::member_function<QByteArray, QByteArray&, int, const QByteArray&, &QByteArray::insert>(c, "insert").create();
  // QByteArray& remove(int, int);
  gonk::bind::member_function<QByteArray, QByteArray&, int, int, &QByteArray::remove>(c, "remove").create();
  // QByteArray& replace(int, int, const char*);
  /// TODO: QByteArray& replace(int, int, const char*);
  // QByteArray& replace(int, int, const char*, int);
  /// TODO: QByteArray& replace(int, int, const char*, int);
  // QByteArray& replace(int, int, const QByteArray&);
  gonk::bind::member_function<QByteArray, QByteArray&, int, int, const QByteArray&, &QByteArray::replace>(c, "replace").create();
  // QByteArray& replace(char, const char*);
  /// TODO: QByteArray& replace(char, const char*);
  // QByteArray& replace(char, const QByteArray&);
  gonk::bind::member_function<QByteArray, QByteArray&, char, const QByteArray&, &QByteArray::replace>(c, "replace").create();
  // QByteArray& replace(const char*, const char*);
  /// TODO: QByteArray& replace(const char*, const char*);
  // QByteArray& replace(const char*, int, const char*, int);
  /// TODO: QByteArray& replace(const char*, int, const char*, int);
  // QByteArray& replace(const QByteArray&, const QByteArray&);
  gonk::bind::member_function<QByteArray, QByteArray&, const QByteArray&, const QByteArray&, &QByteArray::replace>(c, "replace").create();
  // QByteArray& replace(const QByteArray&, const char*);
  /// TODO: QByteArray& replace(const QByteArray&, const char*);
  // QByteArray& replace(const char*, const QByteArray&);
  /// TODO: QByteArray& replace(const char*, const QByteArray&);
  // QByteArray& replace(char, char);
  gonk::bind::member_function<QByteArray, QByteArray&, char, char, &QByteArray::replace>(c, "replace").create();
  // QByteArray& operator+=(char);
  gonk::bind::memop_add_assign<QByteArray, char>(c);
  // QByteArray& operator+=(const char*);
  /// TODO: QByteArray& operator+=(const char*);
  // QByteArray& operator+=(const QByteArray&);
  gonk::bind::memop_add_assign<QByteArray, const QByteArray&>(c);
  // QList<QByteArray> split(char) const;
  /// TODO: QList<QByteArray> split(char) const;
  // QByteArray repeated(int) const;
  gonk::bind::member_function<QByteArray, QByteArray, int, &QByteArray::repeated>(c, "repeated").create();
  // QByteArray& append(const QString&);
  gonk::bind::member_function<QByteArray, QByteArray&, const QString&, &QByteArray::append>(c, "append").create();
  // QByteArray& insert(int, const QString&);
  gonk::bind::member_function<QByteArray, QByteArray&, int, const QString&, &QByteArray::insert>(c, "insert").create();
  // QByteArray& replace(const QString&, const char*);
  /// TODO: QByteArray& replace(const QString&, const char*);
  // QByteArray& replace(char, const QString&);
  gonk::bind::member_function<QByteArray, QByteArray&, char, const QString&, &QByteArray::replace>(c, "replace").create();
  // QByteArray& replace(const QString&, const QByteArray&);
  gonk::bind::member_function<QByteArray, QByteArray&, const QString&, const QByteArray&, &QByteArray::replace>(c, "replace").create();
  // QByteArray& operator+=(const QString&);
  gonk::bind::memop_add_assign<QByteArray, const QString&>(c);
  // int indexOf(const QString&, int) const;
  gonk::bind::member_function<QByteArray, int, const QString&, int, &QByteArray::indexOf>(c, "indexOf").create();
  // int lastIndexOf(const QString&, int) const;
  gonk::bind::member_function<QByteArray, int, const QString&, int, &QByteArray::lastIndexOf>(c, "lastIndexOf").create();
  // bool operator==(const QString&) const;
  gonk::bind::memop_eq<QByteArray, const QString&>(c);
  // bool operator!=(const QString&) const;
  gonk::bind::memop_neq<QByteArray, const QString&>(c);
  // bool operator<(const QString&) const;
  gonk::bind::memop_less<QByteArray, const QString&>(c);
  // bool operator>(const QString&) const;
  gonk::bind::memop_greater<QByteArray, const QString&>(c);
  // bool operator<=(const QString&) const;
  gonk::bind::memop_leq<QByteArray, const QString&>(c);
  // bool operator>=(const QString&) const;
  gonk::bind::memop_geq<QByteArray, const QString&>(c);
  // short toShort(bool*, int) const;
  /// TODO: short toShort(bool*, int) const;
  // ushort toUShort(bool*, int) const;
  /// TODO: ushort toUShort(bool*, int) const;
  // int toInt(bool*, int) const;
  /// TODO: int toInt(bool*, int) const;
  // uint toUInt(bool*, int) const;
  /// TODO: uint toUInt(bool*, int) const;
  // long toLong(bool*, int) const;
  /// TODO: long toLong(bool*, int) const;
  // ulong toULong(bool*, int) const;
  /// TODO: ulong toULong(bool*, int) const;
  // qlonglong toLongLong(bool*, int) const;
  /// TODO: qlonglong toLongLong(bool*, int) const;
  // qulonglong toULongLong(bool*, int) const;
  /// TODO: qulonglong toULongLong(bool*, int) const;
  // float toFloat(bool*) const;
  /// TODO: float toFloat(bool*) const;
  // double toDouble(bool*) const;
  /// TODO: double toDouble(bool*) const;
  // QByteArray toBase64(QByteArray::Base64Options) const;
  /// TODO: QByteArray toBase64(QByteArray::Base64Options) const;
  // QByteArray toBase64() const;
  gonk::bind::member_function<QByteArray, QByteArray, &QByteArray::toBase64>(c, "toBase64").create();
  // QByteArray toHex() const;
  gonk::bind::member_function<QByteArray, QByteArray, &QByteArray::toHex>(c, "toHex").create();
  // QByteArray toHex(char) const;
  gonk::bind::member_function<QByteArray, QByteArray, char, &QByteArray::toHex>(c, "toHex").create();
  // QByteArray toPercentEncoding(const QByteArray&, const QByteArray&, char) const;
  gonk::bind::member_function<QByteArray, QByteArray, const QByteArray&, const QByteArray&, char, &QByteArray::toPercentEncoding>(c, "toPercentEncoding").create();
  // QByteArray& setNum(short, int);
  /// TODO: QByteArray& setNum(short, int);
  // QByteArray& setNum(ushort, int);
  /// TODO: QByteArray& setNum(ushort, int);
  // QByteArray& setNum(int, int);
  gonk::bind::member_function<QByteArray, QByteArray&, int, int, &QByteArray::setNum>(c, "setNum").create();
  // QByteArray& setNum(uint, int);
  /// TODO: QByteArray& setNum(uint, int);
  // QByteArray& setNum(qlonglong, int);
  /// TODO: QByteArray& setNum(qlonglong, int);
  // QByteArray& setNum(qulonglong, int);
  /// TODO: QByteArray& setNum(qulonglong, int);
  // QByteArray& setNum(float, char, int);
  gonk::bind::member_function<QByteArray, QByteArray&, float, char, int, &QByteArray::setNum>(c, "setNum").create();
  // QByteArray& setNum(double, char, int);
  gonk::bind::member_function<QByteArray, QByteArray&, double, char, int, &QByteArray::setNum>(c, "setNum").create();
  // QByteArray& setRawData(const char*, uint);
  /// TODO: QByteArray& setRawData(const char*, uint);
  // static QByteArray number(int, int);
  gonk::bind::static_member_function<QByteArray, QByteArray, int, int, &QByteArray::number>(c, "number").create();
  // static QByteArray number(uint, int);
  /// TODO: static QByteArray number(uint, int);
  // static QByteArray number(qlonglong, int);
  /// TODO: static QByteArray number(qlonglong, int);
  // static QByteArray number(qulonglong, int);
  /// TODO: static QByteArray number(qulonglong, int);
  // static QByteArray number(double, char, int);
  gonk::bind::static_member_function<QByteArray, QByteArray, double, char, int, &QByteArray::number>(c, "number").create();
  // static QByteArray fromRawData(const char*, int);
  /// TODO: static QByteArray fromRawData(const char*, int);
  // static QByteArray fromBase64(const QByteArray&, QByteArray::Base64Options);
  /// TODO: static QByteArray fromBase64(const QByteArray&, QByteArray::Base64Options);
  // static QByteArray fromBase64(const QByteArray&);
  gonk::bind::static_member_function<QByteArray, QByteArray, const QByteArray&, &QByteArray::fromBase64>(c, "fromBase64").create();
  // static QByteArray fromHex(const QByteArray&);
  gonk::bind::static_member_function<QByteArray, QByteArray, const QByteArray&, &QByteArray::fromHex>(c, "fromHex").create();
  // static QByteArray fromPercentEncoding(const QByteArray&, char);
  gonk::bind::static_member_function<QByteArray, QByteArray, const QByteArray&, char, &QByteArray::fromPercentEncoding>(c, "fromPercentEncoding").create();
  // QByteArray::iterator begin();
  /// TODO: QByteArray::iterator begin();
  // QByteArray::const_iterator begin() const;
  /// TODO: QByteArray::const_iterator begin() const;
  // QByteArray::const_iterator cbegin() const;
  /// TODO: QByteArray::const_iterator cbegin() const;
  // QByteArray::const_iterator constBegin() const;
  /// TODO: QByteArray::const_iterator constBegin() const;
  // QByteArray::iterator end();
  /// TODO: QByteArray::iterator end();
  // QByteArray::const_iterator end() const;
  /// TODO: QByteArray::const_iterator end() const;
  // QByteArray::const_iterator cend() const;
  /// TODO: QByteArray::const_iterator cend() const;
  // QByteArray::const_iterator constEnd() const;
  /// TODO: QByteArray::const_iterator constEnd() const;
  // QByteArray::reverse_iterator rbegin();
  /// TODO: QByteArray::reverse_iterator rbegin();
  // QByteArray::reverse_iterator rend();
  /// TODO: QByteArray::reverse_iterator rend();
  // QByteArray::const_reverse_iterator rbegin() const;
  /// TODO: QByteArray::const_reverse_iterator rbegin() const;
  // QByteArray::const_reverse_iterator rend() const;
  /// TODO: QByteArray::const_reverse_iterator rend() const;
  // QByteArray::const_reverse_iterator crbegin() const;
  /// TODO: QByteArray::const_reverse_iterator crbegin() const;
  // QByteArray::const_reverse_iterator crend() const;
  /// TODO: QByteArray::const_reverse_iterator crend() const;
  // void push_back(char);
  gonk::bind::void_member_function<QByteArray, char, &QByteArray::push_back>(c, "push_back").create();
  // void push_back(const char*);
  /// TODO: void push_back(const char*);
  // void push_back(const QByteArray&);
  gonk::bind::void_member_function<QByteArray, const QByteArray&, &QByteArray::push_back>(c, "push_back").create();
  // void push_front(char);
  gonk::bind::void_member_function<QByteArray, char, &QByteArray::push_front>(c, "push_front").create();
  // void push_front(const char*);
  /// TODO: void push_front(const char*);
  // void push_front(const QByteArray&);
  gonk::bind::void_member_function<QByteArray, const QByteArray&, &QByteArray::push_front>(c, "push_front").create();
  // void shrink_to_fit();
  gonk::bind::void_member_function<QByteArray, &QByteArray::shrink_to_fit>(c, "shrink_to_fit").create();
  // static QByteArray fromStdString(const std::string&);
  gonk::bind::static_member_function<QByteArray, QByteArray, const std::string&, &QByteArray::fromStdString>(c, "fromStdString").create();
  // std::string toStdString() const;
  gonk::bind::member_function<QByteArray, std::string, &QByteArray::toStdString>(c, "toStdString").create();
  // int count() const;
  gonk::bind::member_function<QByteArray, int, &QByteArray::count>(c, "count").create();
  // int length() const;
  gonk::bind::member_function<QByteArray, int, &QByteArray::length>(c, "length").create();
  // bool isNull() const;
  gonk::bind::member_function<QByteArray, bool, &QByteArray::isNull>(c, "isNull").create();
  // QByteArray(QByteArrayDataPtr);
  /// TODO: QByteArray(QByteArrayDataPtr);
}



static void register_byte_ref(script::Namespace& parent)
{
  using namespace script;
  
  Class byte_ref = parent.newClass("QByteRef").setId(script::Type::make<QByteRef>().data())
    .get();

  Class& c = byte_ref;
  

  // QByteRef& operator=(char);
  gonk::bind::memop_assign<QByteRef, char>(c);
  // QByteRef& operator=(const QByteRef&);
  gonk::bind::memop_assign<QByteRef, const QByteRef&>(c);
  // bool operator==(char) const;
  gonk::bind::memop_eq<QByteRef, char>(c);
  // bool operator!=(char) const;
  gonk::bind::memop_neq<QByteRef, char>(c);
  // bool operator>(char) const;
  gonk::bind::memop_greater<QByteRef, char>(c);
  // bool operator>=(char) const;
  gonk::bind::memop_geq<QByteRef, char>(c);
  // bool operator<(char) const;
  gonk::bind::memop_less<QByteRef, char>(c);
  // bool operator<=(char) const;
  gonk::bind::memop_leq<QByteRef, char>(c);
}

#endif // METAGONK_SOURCE

namespace {
int bytearray_qstrcmp(const QByteArray& a1, const QByteArray& a2)
{
  return qstrcmp(a1, a2);
}

QByteArray bytearray_qCompress(const QByteArray& a1, int a2)
{
  return qCompress(a1, a2);
}

QByteArray bytearray_qUncompress(const QByteArray& a1)
{
  return qUncompress(a1);
}

}

void register_bytearray_file(script::Namespace ns)
{
  using namespace script;


  register_byte_array(ns);
  register_byte_ref(ns);

  // char* qstrdup(const char*);
  /// TODO: char* qstrdup(const char*);
  // uint qstrlen(const char*);
  /// TODO: uint qstrlen(const char*);
  // uint qstrnlen(const char*, uint);
  /// TODO: uint qstrnlen(const char*, uint);
  // char* qstrcpy(char*, const char*);
  /// TODO: char* qstrcpy(char*, const char*);
  // char* qstrncpy(char*, const char*, uint);
  /// TODO: char* qstrncpy(char*, const char*, uint);
  // int qstrcmp(const char*, const char*);
  /// TODO: int qstrcmp(const char*, const char*);
  // int qstrcmp(const QByteArray&, const QByteArray&);
  gonk::bind::free_function<int, const QByteArray&, const QByteArray&, &bytearray_qstrcmp>(ns, "qstrcmp").create();
  // int qstrcmp(const QByteArray&, const char*);
  /// TODO: int qstrcmp(const QByteArray&, const char*);
  // int qstrcmp(const char*, const QByteArray&);
  /// TODO: int qstrcmp(const char*, const QByteArray&);
  // int qstrncmp(const char*, const char*, uint);
  /// TODO: int qstrncmp(const char*, const char*, uint);
  // int qstricmp(const char*, const char*);
  /// TODO: int qstricmp(const char*, const char*);
  // int qstrnicmp(const char*, const char*, uint);
  /// TODO: int qstrnicmp(const char*, const char*, uint);
  // int qvsnprintf(char*, size_t, const char*, va_list);
  /// TODO: int qvsnprintf(char*, size_t, const char*, va_list);
  // int qsnprintf(char*, size_t, const char*);
  /// TODO: int qsnprintf(char*, size_t, const char*);
  // quint16 qChecksum(const char*, uint);
  /// TODO: quint16 qChecksum(const char*, uint);
  // quint16 qChecksum(const char*, uint, Qt::ChecksumType);
  /// TODO: quint16 qChecksum(const char*, uint, Qt::ChecksumType);
  // QFlags<QByteArray::Base64Options::enum_type> operator|(QByteArray::Base64Options::enum_type, QByteArray::Base64Options::enum_type);
  /// TODO: QFlags<QByteArray::Base64Options::enum_type> operator|(QByteArray::Base64Options::enum_type, QByteArray::Base64Options::enum_type);
  // QFlags<QByteArray::Base64Options::enum_type> operator|(QByteArray::Base64Options::enum_type, QFlags<QByteArray::Base64Options::enum_type>);
  /// TODO: QFlags<QByteArray::Base64Options::enum_type> operator|(QByteArray::Base64Options::enum_type, QFlags<QByteArray::Base64Options::enum_type>);
  // QIncompatibleFlag operator|(QByteArray::Base64Options::enum_type, int);
  /// TODO: QIncompatibleFlag operator|(QByteArray::Base64Options::enum_type, int);
  // bool operator==(const QByteArray&, const QByteArray&);
  gonk::bind::op_eq<const QByteArray&, const QByteArray&>(ns);
  // bool operator==(const QByteArray&, const char*);
  /// TODO: bool operator==(const QByteArray&, const char*);
  // bool operator==(const char*, const QByteArray&);
  /// TODO: bool operator==(const char*, const QByteArray&);
  // bool operator!=(const QByteArray&, const QByteArray&);
  gonk::bind::op_neq<const QByteArray&, const QByteArray&>(ns);
  // bool operator!=(const QByteArray&, const char*);
  /// TODO: bool operator!=(const QByteArray&, const char*);
  // bool operator!=(const char*, const QByteArray&);
  /// TODO: bool operator!=(const char*, const QByteArray&);
  // bool operator<(const QByteArray&, const QByteArray&);
  gonk::bind::op_less<const QByteArray&, const QByteArray&>(ns);
  // bool operator<(const QByteArray&, const char*);
  /// TODO: bool operator<(const QByteArray&, const char*);
  // bool operator<(const char*, const QByteArray&);
  /// TODO: bool operator<(const char*, const QByteArray&);
  // bool operator<=(const QByteArray&, const QByteArray&);
  gonk::bind::op_leq<const QByteArray&, const QByteArray&>(ns);
  // bool operator<=(const QByteArray&, const char*);
  /// TODO: bool operator<=(const QByteArray&, const char*);
  // bool operator<=(const char*, const QByteArray&);
  /// TODO: bool operator<=(const char*, const QByteArray&);
  // bool operator>(const QByteArray&, const QByteArray&);
  gonk::bind::op_greater<const QByteArray&, const QByteArray&>(ns);
  // bool operator>(const QByteArray&, const char*);
  /// TODO: bool operator>(const QByteArray&, const char*);
  // bool operator>(const char*, const QByteArray&);
  /// TODO: bool operator>(const char*, const QByteArray&);
  // bool operator>=(const QByteArray&, const QByteArray&);
  gonk::bind::op_geq<const QByteArray&, const QByteArray&>(ns);
  // bool operator>=(const QByteArray&, const char*);
  /// TODO: bool operator>=(const QByteArray&, const char*);
  // bool operator>=(const char*, const QByteArray&);
  /// TODO: bool operator>=(const char*, const QByteArray&);
  // const QByteArray operator+(const QByteArray&, const QByteArray&);
  gonk::bind::op_add<const QByteArray, const QByteArray&, const QByteArray&>(ns);
  // const QByteArray operator+(const QByteArray&, const char*);
  /// TODO: const QByteArray operator+(const QByteArray&, const char*);
  // const QByteArray operator+(const QByteArray&, char);
  gonk::bind::op_add<const QByteArray, const QByteArray&, char>(ns);
  // const QByteArray operator+(const char*, const QByteArray&);
  /// TODO: const QByteArray operator+(const char*, const QByteArray&);
  // const QByteArray operator+(char, const QByteArray&);
  gonk::bind::op_add<const QByteArray, char, const QByteArray&>(ns);
  // QDataStream& operator<<(QDataStream&, const QByteArray&);
  /// TODO: QDataStream& operator<<(QDataStream&, const QByteArray&);
  // QDataStream& operator>>(QDataStream&, QByteArray&);
  /// TODO: QDataStream& operator>>(QDataStream&, QByteArray&);
  // QByteArray qCompress(const QByteArray&, int);
  gonk::bind::free_function<QByteArray, const QByteArray&, int, &bytearray_qCompress>(ns, "qCompress").create();
  // QByteArray qUncompress(const QByteArray&);
  gonk::bind::free_function<QByteArray, const QByteArray&, &bytearray_qUncompress>(ns, "qUncompress").create();
  // void swap(QByteArray&, QByteArray&);
  gonk::bind::void_function<QByteArray&, QByteArray&, &swap>(ns, "swap").create();
}
