// Copyright (C) 2020 Vincent Chambrin
// This file is part of the 'gonk' project
// For conditions of distribution and use, see copyright notice in LICENSE

// Warning: This file was generated by metagonk, all modifications will be lost. //

#include "char_.h"

#include "gonk/common/binding/class.h"
#include "gonk/common/binding/namespace.h"
#include "gonk/common/enums.h"

#include <script/classbuilder.h>
#include <script/enumbuilder.h>

#include "qt-core/char_.h"
#include "qt-core/string.h"

static void register_latin1_char_class(script::Namespace ns)
{
  using namespace script;

  Class latin1_char = ns.newClass("QLatin1Char").setId(script::Type::make<QLatin1Char>().data()).get();


  // QLatin1Char(char);
  gonk::bind::constructor<QLatin1Char, char>(latin1_char).create();
  // char toLatin1() const;
  gonk::bind::member_function<QLatin1Char, char, &QLatin1Char::toLatin1>(latin1_char, "toLatin1").create();
  // ushort unicode() const;
  /// TODO: ushort unicode() const;
}


static void register_char__special_character_enum(script::Class char_)
{
  using namespace script;

  Enum special_character = char_.newEnum("SpecialCharacter").setId(script::Type::make<QChar::SpecialCharacter>().data()).get();

  special_character.addValue("Null", QChar::Null);
  special_character.addValue("Tabulation", QChar::Tabulation);
  special_character.addValue("LineFeed", QChar::LineFeed);
  special_character.addValue("CarriageReturn", QChar::CarriageReturn);
  special_character.addValue("Space", QChar::Space);
  special_character.addValue("Nbsp", QChar::Nbsp);
  special_character.addValue("SoftHyphen", QChar::SoftHyphen);
  special_character.addValue("ReplacementCharacter", QChar::ReplacementCharacter);
  special_character.addValue("ObjectReplacementCharacter", QChar::ObjectReplacementCharacter);
  special_character.addValue("ByteOrderMark", QChar::ByteOrderMark);
  special_character.addValue("ByteOrderSwapped", QChar::ByteOrderSwapped);
  special_character.addValue("ParagraphSeparator", QChar::ParagraphSeparator);
  special_character.addValue("LineSeparator", QChar::LineSeparator);
  special_character.addValue("LastValidCodePoint", QChar::LastValidCodePoint);
}


static void register_char__category_enum(script::Class char_)
{
  using namespace script;

  Enum category = char_.newEnum("Category").setId(script::Type::make<QChar::Category>().data()).get();

  category.addValue("Mark_NonSpacing", QChar::Mark_NonSpacing);
  category.addValue("Mark_SpacingCombining", QChar::Mark_SpacingCombining);
  category.addValue("Mark_Enclosing", QChar::Mark_Enclosing);
  category.addValue("Number_DecimalDigit", QChar::Number_DecimalDigit);
  category.addValue("Number_Letter", QChar::Number_Letter);
  category.addValue("Number_Other", QChar::Number_Other);
  category.addValue("Separator_Space", QChar::Separator_Space);
  category.addValue("Separator_Line", QChar::Separator_Line);
  category.addValue("Separator_Paragraph", QChar::Separator_Paragraph);
  category.addValue("Other_Control", QChar::Other_Control);
  category.addValue("Other_Format", QChar::Other_Format);
  category.addValue("Other_Surrogate", QChar::Other_Surrogate);
  category.addValue("Other_PrivateUse", QChar::Other_PrivateUse);
  category.addValue("Other_NotAssigned", QChar::Other_NotAssigned);
  category.addValue("Letter_Uppercase", QChar::Letter_Uppercase);
  category.addValue("Letter_Lowercase", QChar::Letter_Lowercase);
  category.addValue("Letter_Titlecase", QChar::Letter_Titlecase);
  category.addValue("Letter_Modifier", QChar::Letter_Modifier);
  category.addValue("Letter_Other", QChar::Letter_Other);
  category.addValue("Punctuation_Connector", QChar::Punctuation_Connector);
  category.addValue("Punctuation_Dash", QChar::Punctuation_Dash);
  category.addValue("Punctuation_Open", QChar::Punctuation_Open);
  category.addValue("Punctuation_Close", QChar::Punctuation_Close);
  category.addValue("Punctuation_InitialQuote", QChar::Punctuation_InitialQuote);
  category.addValue("Punctuation_FinalQuote", QChar::Punctuation_FinalQuote);
  category.addValue("Punctuation_Other", QChar::Punctuation_Other);
  category.addValue("Symbol_Math", QChar::Symbol_Math);
  category.addValue("Symbol_Currency", QChar::Symbol_Currency);
  category.addValue("Symbol_Modifier", QChar::Symbol_Modifier);
  category.addValue("Symbol_Other", QChar::Symbol_Other);
}


static void register_char__script_enum(script::Class char_)
{
  using namespace script;

  Enum script = char_.newEnum("Script").setId(script::Type::make<QChar::Script>().data()).get();

  script.addValue("Script_Unknown", QChar::Script_Unknown);
  script.addValue("Script_Inherited", QChar::Script_Inherited);
  script.addValue("Script_Common", QChar::Script_Common);
  script.addValue("Script_Latin", QChar::Script_Latin);
  script.addValue("Script_Greek", QChar::Script_Greek);
  script.addValue("Script_Cyrillic", QChar::Script_Cyrillic);
  script.addValue("Script_Armenian", QChar::Script_Armenian);
  script.addValue("Script_Hebrew", QChar::Script_Hebrew);
  script.addValue("Script_Arabic", QChar::Script_Arabic);
  script.addValue("Script_Syriac", QChar::Script_Syriac);
  script.addValue("Script_Thaana", QChar::Script_Thaana);
  script.addValue("Script_Devanagari", QChar::Script_Devanagari);
  script.addValue("Script_Bengali", QChar::Script_Bengali);
  script.addValue("Script_Gurmukhi", QChar::Script_Gurmukhi);
  script.addValue("Script_Gujarati", QChar::Script_Gujarati);
  script.addValue("Script_Oriya", QChar::Script_Oriya);
  script.addValue("Script_Tamil", QChar::Script_Tamil);
  script.addValue("Script_Telugu", QChar::Script_Telugu);
  script.addValue("Script_Kannada", QChar::Script_Kannada);
  script.addValue("Script_Malayalam", QChar::Script_Malayalam);
  script.addValue("Script_Sinhala", QChar::Script_Sinhala);
  script.addValue("Script_Thai", QChar::Script_Thai);
  script.addValue("Script_Lao", QChar::Script_Lao);
  script.addValue("Script_Tibetan", QChar::Script_Tibetan);
  script.addValue("Script_Myanmar", QChar::Script_Myanmar);
  script.addValue("Script_Georgian", QChar::Script_Georgian);
  script.addValue("Script_Hangul", QChar::Script_Hangul);
  script.addValue("Script_Ethiopic", QChar::Script_Ethiopic);
  script.addValue("Script_Cherokee", QChar::Script_Cherokee);
  script.addValue("Script_CanadianAboriginal", QChar::Script_CanadianAboriginal);
  script.addValue("Script_Ogham", QChar::Script_Ogham);
  script.addValue("Script_Runic", QChar::Script_Runic);
  script.addValue("Script_Khmer", QChar::Script_Khmer);
  script.addValue("Script_Mongolian", QChar::Script_Mongolian);
  script.addValue("Script_Hiragana", QChar::Script_Hiragana);
  script.addValue("Script_Katakana", QChar::Script_Katakana);
  script.addValue("Script_Bopomofo", QChar::Script_Bopomofo);
  script.addValue("Script_Han", QChar::Script_Han);
  script.addValue("Script_Yi", QChar::Script_Yi);
  script.addValue("Script_OldItalic", QChar::Script_OldItalic);
  script.addValue("Script_Gothic", QChar::Script_Gothic);
  script.addValue("Script_Deseret", QChar::Script_Deseret);
  script.addValue("Script_Tagalog", QChar::Script_Tagalog);
  script.addValue("Script_Hanunoo", QChar::Script_Hanunoo);
  script.addValue("Script_Buhid", QChar::Script_Buhid);
  script.addValue("Script_Tagbanwa", QChar::Script_Tagbanwa);
  script.addValue("Script_Coptic", QChar::Script_Coptic);
  script.addValue("Script_Limbu", QChar::Script_Limbu);
  script.addValue("Script_TaiLe", QChar::Script_TaiLe);
  script.addValue("Script_LinearB", QChar::Script_LinearB);
  script.addValue("Script_Ugaritic", QChar::Script_Ugaritic);
  script.addValue("Script_Shavian", QChar::Script_Shavian);
  script.addValue("Script_Osmanya", QChar::Script_Osmanya);
  script.addValue("Script_Cypriot", QChar::Script_Cypriot);
  script.addValue("Script_Braille", QChar::Script_Braille);
  script.addValue("Script_Buginese", QChar::Script_Buginese);
  script.addValue("Script_NewTaiLue", QChar::Script_NewTaiLue);
  script.addValue("Script_Glagolitic", QChar::Script_Glagolitic);
  script.addValue("Script_Tifinagh", QChar::Script_Tifinagh);
  script.addValue("Script_SylotiNagri", QChar::Script_SylotiNagri);
  script.addValue("Script_OldPersian", QChar::Script_OldPersian);
  script.addValue("Script_Kharoshthi", QChar::Script_Kharoshthi);
  script.addValue("Script_Balinese", QChar::Script_Balinese);
  script.addValue("Script_Cuneiform", QChar::Script_Cuneiform);
  script.addValue("Script_Phoenician", QChar::Script_Phoenician);
  script.addValue("Script_PhagsPa", QChar::Script_PhagsPa);
  script.addValue("Script_Nko", QChar::Script_Nko);
  script.addValue("Script_Sundanese", QChar::Script_Sundanese);
  script.addValue("Script_Lepcha", QChar::Script_Lepcha);
  script.addValue("Script_OlChiki", QChar::Script_OlChiki);
  script.addValue("Script_Vai", QChar::Script_Vai);
  script.addValue("Script_Saurashtra", QChar::Script_Saurashtra);
  script.addValue("Script_KayahLi", QChar::Script_KayahLi);
  script.addValue("Script_Rejang", QChar::Script_Rejang);
  script.addValue("Script_Lycian", QChar::Script_Lycian);
  script.addValue("Script_Carian", QChar::Script_Carian);
  script.addValue("Script_Lydian", QChar::Script_Lydian);
  script.addValue("Script_Cham", QChar::Script_Cham);
  script.addValue("Script_TaiTham", QChar::Script_TaiTham);
  script.addValue("Script_TaiViet", QChar::Script_TaiViet);
  script.addValue("Script_Avestan", QChar::Script_Avestan);
  script.addValue("Script_EgyptianHieroglyphs", QChar::Script_EgyptianHieroglyphs);
  script.addValue("Script_Samaritan", QChar::Script_Samaritan);
  script.addValue("Script_Lisu", QChar::Script_Lisu);
  script.addValue("Script_Bamum", QChar::Script_Bamum);
  script.addValue("Script_Javanese", QChar::Script_Javanese);
  script.addValue("Script_MeeteiMayek", QChar::Script_MeeteiMayek);
  script.addValue("Script_ImperialAramaic", QChar::Script_ImperialAramaic);
  script.addValue("Script_OldSouthArabian", QChar::Script_OldSouthArabian);
  script.addValue("Script_InscriptionalParthian", QChar::Script_InscriptionalParthian);
  script.addValue("Script_InscriptionalPahlavi", QChar::Script_InscriptionalPahlavi);
  script.addValue("Script_OldTurkic", QChar::Script_OldTurkic);
  script.addValue("Script_Kaithi", QChar::Script_Kaithi);
  script.addValue("Script_Batak", QChar::Script_Batak);
  script.addValue("Script_Brahmi", QChar::Script_Brahmi);
  script.addValue("Script_Mandaic", QChar::Script_Mandaic);
  script.addValue("Script_Chakma", QChar::Script_Chakma);
  script.addValue("Script_MeroiticCursive", QChar::Script_MeroiticCursive);
  script.addValue("Script_MeroiticHieroglyphs", QChar::Script_MeroiticHieroglyphs);
  script.addValue("Script_Miao", QChar::Script_Miao);
  script.addValue("Script_Sharada", QChar::Script_Sharada);
  script.addValue("Script_SoraSompeng", QChar::Script_SoraSompeng);
  script.addValue("Script_Takri", QChar::Script_Takri);
  script.addValue("Script_CaucasianAlbanian", QChar::Script_CaucasianAlbanian);
  script.addValue("Script_BassaVah", QChar::Script_BassaVah);
  script.addValue("Script_Duployan", QChar::Script_Duployan);
  script.addValue("Script_Elbasan", QChar::Script_Elbasan);
  script.addValue("Script_Grantha", QChar::Script_Grantha);
  script.addValue("Script_PahawhHmong", QChar::Script_PahawhHmong);
  script.addValue("Script_Khojki", QChar::Script_Khojki);
  script.addValue("Script_LinearA", QChar::Script_LinearA);
  script.addValue("Script_Mahajani", QChar::Script_Mahajani);
  script.addValue("Script_Manichaean", QChar::Script_Manichaean);
  script.addValue("Script_MendeKikakui", QChar::Script_MendeKikakui);
  script.addValue("Script_Modi", QChar::Script_Modi);
  script.addValue("Script_Mro", QChar::Script_Mro);
  script.addValue("Script_OldNorthArabian", QChar::Script_OldNorthArabian);
  script.addValue("Script_Nabataean", QChar::Script_Nabataean);
  script.addValue("Script_Palmyrene", QChar::Script_Palmyrene);
  script.addValue("Script_PauCinHau", QChar::Script_PauCinHau);
  script.addValue("Script_OldPermic", QChar::Script_OldPermic);
  script.addValue("Script_PsalterPahlavi", QChar::Script_PsalterPahlavi);
  script.addValue("Script_Siddham", QChar::Script_Siddham);
  script.addValue("Script_Khudawadi", QChar::Script_Khudawadi);
  script.addValue("Script_Tirhuta", QChar::Script_Tirhuta);
  script.addValue("Script_WarangCiti", QChar::Script_WarangCiti);
  script.addValue("Script_Ahom", QChar::Script_Ahom);
  script.addValue("Script_AnatolianHieroglyphs", QChar::Script_AnatolianHieroglyphs);
  script.addValue("Script_Hatran", QChar::Script_Hatran);
  script.addValue("Script_Multani", QChar::Script_Multani);
  script.addValue("Script_OldHungarian", QChar::Script_OldHungarian);
  script.addValue("Script_SignWriting", QChar::Script_SignWriting);
  script.addValue("ScriptCount", QChar::ScriptCount);
}


static void register_char__direction_enum(script::Class char_)
{
  using namespace script;

  Enum direction = char_.newEnum("Direction").setId(script::Type::make<QChar::Direction>().data()).get();

  direction.addValue("DirL", QChar::DirL);
  direction.addValue("DirR", QChar::DirR);
  direction.addValue("DirEN", QChar::DirEN);
  direction.addValue("DirES", QChar::DirES);
  direction.addValue("DirET", QChar::DirET);
  direction.addValue("DirAN", QChar::DirAN);
  direction.addValue("DirCS", QChar::DirCS);
  direction.addValue("DirB", QChar::DirB);
  direction.addValue("DirS", QChar::DirS);
  direction.addValue("DirWS", QChar::DirWS);
  direction.addValue("DirON", QChar::DirON);
  direction.addValue("DirLRE", QChar::DirLRE);
  direction.addValue("DirLRO", QChar::DirLRO);
  direction.addValue("DirAL", QChar::DirAL);
  direction.addValue("DirRLE", QChar::DirRLE);
  direction.addValue("DirRLO", QChar::DirRLO);
  direction.addValue("DirPDF", QChar::DirPDF);
  direction.addValue("DirNSM", QChar::DirNSM);
  direction.addValue("DirBN", QChar::DirBN);
  direction.addValue("DirLRI", QChar::DirLRI);
  direction.addValue("DirRLI", QChar::DirRLI);
  direction.addValue("DirFSI", QChar::DirFSI);
  direction.addValue("DirPDI", QChar::DirPDI);
}


static void register_char__decomposition_enum(script::Class char_)
{
  using namespace script;

  Enum decomposition = char_.newEnum("Decomposition").setId(script::Type::make<QChar::Decomposition>().data()).get();

  decomposition.addValue("NoDecomposition", QChar::NoDecomposition);
  decomposition.addValue("Canonical", QChar::Canonical);
  decomposition.addValue("Font", QChar::Font);
  decomposition.addValue("NoBreak", QChar::NoBreak);
  decomposition.addValue("Initial", QChar::Initial);
  decomposition.addValue("Medial", QChar::Medial);
  decomposition.addValue("Final", QChar::Final);
  decomposition.addValue("Isolated", QChar::Isolated);
  decomposition.addValue("Circle", QChar::Circle);
  decomposition.addValue("Super", QChar::Super);
  decomposition.addValue("Sub", QChar::Sub);
  decomposition.addValue("Vertical", QChar::Vertical);
  decomposition.addValue("Wide", QChar::Wide);
  decomposition.addValue("Narrow", QChar::Narrow);
  decomposition.addValue("Small", QChar::Small);
  decomposition.addValue("Square", QChar::Square);
  decomposition.addValue("Compat", QChar::Compat);
  decomposition.addValue("Fraction", QChar::Fraction);
}


static void register_char__joining_type_enum(script::Class char_)
{
  using namespace script;

  Enum joining_type = char_.newEnum("JoiningType").setId(script::Type::make<QChar::JoiningType>().data()).get();

  joining_type.addValue("Joining_None", QChar::Joining_None);
  joining_type.addValue("Joining_Causing", QChar::Joining_Causing);
  joining_type.addValue("Joining_Dual", QChar::Joining_Dual);
  joining_type.addValue("Joining_Right", QChar::Joining_Right);
  joining_type.addValue("Joining_Left", QChar::Joining_Left);
  joining_type.addValue("Joining_Transparent", QChar::Joining_Transparent);
}


static void register_char__joining_enum(script::Class char_)
{
  using namespace script;

  Enum joining = char_.newEnum("Joining").setId(script::Type::make<QChar::Joining>().data()).get();

  joining.addValue("OtherJoining", QChar::OtherJoining);
  joining.addValue("Dual", QChar::Dual);
  joining.addValue("Right", QChar::Right);
  joining.addValue("Center", QChar::Center);
}


static void register_char__combining_class_enum(script::Class char_)
{
  using namespace script;

  Enum combining_class = char_.newEnum("CombiningClass").setId(script::Type::make<QChar::CombiningClass>().data()).get();

  combining_class.addValue("Combining_BelowLeftAttached", QChar::Combining_BelowLeftAttached);
  combining_class.addValue("Combining_BelowAttached", QChar::Combining_BelowAttached);
  combining_class.addValue("Combining_BelowRightAttached", QChar::Combining_BelowRightAttached);
  combining_class.addValue("Combining_LeftAttached", QChar::Combining_LeftAttached);
  combining_class.addValue("Combining_RightAttached", QChar::Combining_RightAttached);
  combining_class.addValue("Combining_AboveLeftAttached", QChar::Combining_AboveLeftAttached);
  combining_class.addValue("Combining_AboveAttached", QChar::Combining_AboveAttached);
  combining_class.addValue("Combining_AboveRightAttached", QChar::Combining_AboveRightAttached);
  combining_class.addValue("Combining_BelowLeft", QChar::Combining_BelowLeft);
  combining_class.addValue("Combining_Below", QChar::Combining_Below);
  combining_class.addValue("Combining_BelowRight", QChar::Combining_BelowRight);
  combining_class.addValue("Combining_Left", QChar::Combining_Left);
  combining_class.addValue("Combining_Right", QChar::Combining_Right);
  combining_class.addValue("Combining_AboveLeft", QChar::Combining_AboveLeft);
  combining_class.addValue("Combining_Above", QChar::Combining_Above);
  combining_class.addValue("Combining_AboveRight", QChar::Combining_AboveRight);
  combining_class.addValue("Combining_DoubleBelow", QChar::Combining_DoubleBelow);
  combining_class.addValue("Combining_DoubleAbove", QChar::Combining_DoubleAbove);
  combining_class.addValue("Combining_IotaSubscript", QChar::Combining_IotaSubscript);
}


static void register_char__unicode_version_enum(script::Class char_)
{
  using namespace script;

  Enum unicode_version = char_.newEnum("UnicodeVersion").setId(script::Type::make<QChar::UnicodeVersion>().data()).get();

  unicode_version.addValue("Unicode_Unassigned", QChar::Unicode_Unassigned);
  unicode_version.addValue("Unicode_1_1", QChar::Unicode_1_1);
  unicode_version.addValue("Unicode_2_0", QChar::Unicode_2_0);
  unicode_version.addValue("Unicode_2_1_2", QChar::Unicode_2_1_2);
  unicode_version.addValue("Unicode_3_0", QChar::Unicode_3_0);
  unicode_version.addValue("Unicode_3_1", QChar::Unicode_3_1);
  unicode_version.addValue("Unicode_3_2", QChar::Unicode_3_2);
  unicode_version.addValue("Unicode_4_0", QChar::Unicode_4_0);
  unicode_version.addValue("Unicode_4_1", QChar::Unicode_4_1);
  unicode_version.addValue("Unicode_5_0", QChar::Unicode_5_0);
  unicode_version.addValue("Unicode_5_1", QChar::Unicode_5_1);
  unicode_version.addValue("Unicode_5_2", QChar::Unicode_5_2);
  unicode_version.addValue("Unicode_6_0", QChar::Unicode_6_0);
  unicode_version.addValue("Unicode_6_1", QChar::Unicode_6_1);
  unicode_version.addValue("Unicode_6_2", QChar::Unicode_6_2);
  unicode_version.addValue("Unicode_6_3", QChar::Unicode_6_3);
  unicode_version.addValue("Unicode_7_0", QChar::Unicode_7_0);
  unicode_version.addValue("Unicode_8_0", QChar::Unicode_8_0);
}


namespace {
QChar::Category QChar_category(const QChar& self)
{
  return self.category();
}

QChar::Direction QChar_direction(const QChar& self)
{
  return self.direction();
}

QChar::JoiningType QChar_joiningType(const QChar& self)
{
  return self.joiningType();
}

QChar::Joining QChar_joining(const QChar& self)
{
  return self.joining();
}

QChar QChar_mirroredChar(const QChar& self)
{
  return self.mirroredChar();
}

bool QChar_hasMirrored(const QChar& self)
{
  return self.hasMirrored();
}

QChar::Decomposition QChar_decompositionTag(const QChar& self)
{
  return self.decompositionTag();
}

int QChar_digitValue(const QChar& self)
{
  return self.digitValue();
}

QChar QChar_toLower(const QChar& self)
{
  return self.toLower();
}

QChar QChar_toUpper(const QChar& self)
{
  return self.toUpper();
}

QChar QChar_toTitleCase(const QChar& self)
{
  return self.toTitleCase();
}

QChar QChar_toCaseFolded(const QChar& self)
{
  return self.toCaseFolded();
}

QChar::Script QChar_script(const QChar& self)
{
  return self.script();
}

QChar::UnicodeVersion QChar_unicodeVersion(const QChar& self)
{
  return self.unicodeVersion();
}

char QChar_toLatin1(const QChar& self)
{
  return self.toLatin1();
}

bool QChar_isNull(const QChar& self)
{
  return self.isNull();
}

bool QChar_isPrint(const QChar& self)
{
  return self.isPrint();
}

bool QChar_isSpace(const QChar& self)
{
  return self.isSpace();
}

bool QChar_isMark(const QChar& self)
{
  return self.isMark();
}

bool QChar_isPunct(const QChar& self)
{
  return self.isPunct();
}

bool QChar_isSymbol(const QChar& self)
{
  return self.isSymbol();
}

bool QChar_isLetter(const QChar& self)
{
  return self.isLetter();
}

bool QChar_isNumber(const QChar& self)
{
  return self.isNumber();
}

bool QChar_isLetterOrNumber(const QChar& self)
{
  return self.isLetterOrNumber();
}

bool QChar_isDigit(const QChar& self)
{
  return self.isDigit();
}

bool QChar_isLower(const QChar& self)
{
  return self.isLower();
}

bool QChar_isUpper(const QChar& self)
{
  return self.isUpper();
}

bool QChar_isTitleCase(const QChar& self)
{
  return self.isTitleCase();
}

bool QChar_isNonCharacter(const QChar& self)
{
  return self.isNonCharacter();
}

bool QChar_isHighSurrogate(const QChar& self)
{
  return self.isHighSurrogate();
}

bool QChar_isLowSurrogate(const QChar& self)
{
  return self.isLowSurrogate();
}

bool QChar_isSurrogate(const QChar& self)
{
  return self.isSurrogate();
}

}

static void register_char__class(script::Namespace ns)
{
  using namespace script;

  Class char_ = ns.newClass("QChar").setId(script::Type::make<QChar>().data()).get();

  register_char__special_character_enum(char_);
  register_char__category_enum(char_);
  register_char__script_enum(char_);
  register_char__direction_enum(char_);
  register_char__decomposition_enum(char_);
  register_char__joining_type_enum(char_);
  register_char__joining_enum(char_);
  register_char__combining_class_enum(char_);
  register_char__unicode_version_enum(char_);

  // QChar();
  gonk::bind::default_constructor<QChar>(char_).create();
  // QChar(ushort);
  /// TODO: QChar(ushort);
  // QChar(uchar, uchar);
  /// TODO: QChar(uchar, uchar);
  // QChar(short);
  /// TODO: QChar(short);
  // QChar(uint);
  /// TODO: QChar(uint);
  // QChar(int);
  gonk::bind::constructor<QChar, int>(char_).create();
  // QChar(QChar::SpecialCharacter);
  gonk::bind::constructor<QChar, QChar::SpecialCharacter>(char_).create();
  // QChar(QLatin1Char);
  gonk::bind::constructor<QChar, QLatin1Char>(char_).create();
  // QChar(char16_t);
  /// TODO: QChar(char16_t);
  // QChar(wchar_t);
  /// TODO: QChar(wchar_t);
  // QChar(char);
  gonk::bind::constructor<QChar, char>(char_).create();
  // QChar(uchar);
  /// TODO: QChar(uchar);
  // QChar::Category category() const;
  gonk::bind::fn_as_memfn<QChar, QChar::Category, &QChar_category>(char_, "category").create();
  // QChar::Direction direction() const;
  gonk::bind::fn_as_memfn<QChar, QChar::Direction, &QChar_direction>(char_, "direction").create();
  // QChar::JoiningType joiningType() const;
  gonk::bind::fn_as_memfn<QChar, QChar::JoiningType, &QChar_joiningType>(char_, "joiningType").create();
  // QChar::Joining joining() const;
  gonk::bind::fn_as_memfn<QChar, QChar::Joining, &QChar_joining>(char_, "joining").create();
  // unsigned char combiningClass() const;
  /// TODO: unsigned char combiningClass() const;
  // QChar mirroredChar() const;
  gonk::bind::fn_as_memfn<QChar, QChar, &QChar_mirroredChar>(char_, "mirroredChar").create();
  // bool hasMirrored() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_hasMirrored>(char_, "hasMirrored").create();
  // QString decomposition() const;
  gonk::bind::member_function<QChar, QString, &QChar::decomposition>(char_, "decomposition").create();
  // QChar::Decomposition decompositionTag() const;
  gonk::bind::fn_as_memfn<QChar, QChar::Decomposition, &QChar_decompositionTag>(char_, "decompositionTag").create();
  // int digitValue() const;
  gonk::bind::fn_as_memfn<QChar, int, &QChar_digitValue>(char_, "digitValue").create();
  // QChar toLower() const;
  gonk::bind::fn_as_memfn<QChar, QChar, &QChar_toLower>(char_, "toLower").create();
  // QChar toUpper() const;
  gonk::bind::fn_as_memfn<QChar, QChar, &QChar_toUpper>(char_, "toUpper").create();
  // QChar toTitleCase() const;
  gonk::bind::fn_as_memfn<QChar, QChar, &QChar_toTitleCase>(char_, "toTitleCase").create();
  // QChar toCaseFolded() const;
  gonk::bind::fn_as_memfn<QChar, QChar, &QChar_toCaseFolded>(char_, "toCaseFolded").create();
  // QChar::Script script() const;
  gonk::bind::fn_as_memfn<QChar, QChar::Script, &QChar_script>(char_, "script").create();
  // QChar::UnicodeVersion unicodeVersion() const;
  gonk::bind::fn_as_memfn<QChar, QChar::UnicodeVersion, &QChar_unicodeVersion>(char_, "unicodeVersion").create();
  // char toLatin1() const;
  gonk::bind::fn_as_memfn<QChar, char, &QChar_toLatin1>(char_, "toLatin1").create();
  // ushort unicode() const;
  /// TODO: ushort unicode() const;
  // ushort& unicode();
  /// TODO: ushort& unicode();
  // static QChar fromLatin1(char);
  gonk::bind::static_member_function<QChar, QChar, char, &QChar::fromLatin1>(char_, "fromLatin1").create();
  // bool isNull() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isNull>(char_, "isNull").create();
  // bool isPrint() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isPrint>(char_, "isPrint").create();
  // bool isSpace() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isSpace>(char_, "isSpace").create();
  // bool isMark() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isMark>(char_, "isMark").create();
  // bool isPunct() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isPunct>(char_, "isPunct").create();
  // bool isSymbol() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isSymbol>(char_, "isSymbol").create();
  // bool isLetter() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isLetter>(char_, "isLetter").create();
  // bool isNumber() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isNumber>(char_, "isNumber").create();
  // bool isLetterOrNumber() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isLetterOrNumber>(char_, "isLetterOrNumber").create();
  // bool isDigit() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isDigit>(char_, "isDigit").create();
  // bool isLower() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isLower>(char_, "isLower").create();
  // bool isUpper() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isUpper>(char_, "isUpper").create();
  // bool isTitleCase() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isTitleCase>(char_, "isTitleCase").create();
  // bool isNonCharacter() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isNonCharacter>(char_, "isNonCharacter").create();
  // bool isHighSurrogate() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isHighSurrogate>(char_, "isHighSurrogate").create();
  // bool isLowSurrogate() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isLowSurrogate>(char_, "isLowSurrogate").create();
  // bool isSurrogate() const;
  gonk::bind::fn_as_memfn<QChar, bool, &QChar_isSurrogate>(char_, "isSurrogate").create();
  // uchar cell() const;
  /// TODO: uchar cell() const;
  // uchar row() const;
  /// TODO: uchar row() const;
  // void setCell(uchar);
  /// TODO: void setCell(uchar);
  // void setRow(uchar);
  /// TODO: void setRow(uchar);
  // static bool isNonCharacter(uint);
  /// TODO: static bool isNonCharacter(uint);
  // static bool isHighSurrogate(uint);
  /// TODO: static bool isHighSurrogate(uint);
  // static bool isLowSurrogate(uint);
  /// TODO: static bool isLowSurrogate(uint);
  // static bool isSurrogate(uint);
  /// TODO: static bool isSurrogate(uint);
  // static bool requiresSurrogates(uint);
  /// TODO: static bool requiresSurrogates(uint);
  // static uint surrogateToUcs4(ushort, ushort);
  /// TODO: static uint surrogateToUcs4(ushort, ushort);
  // static uint surrogateToUcs4(QChar, QChar);
  /// TODO: static uint surrogateToUcs4(QChar, QChar);
  // static ushort highSurrogate(uint);
  /// TODO: static ushort highSurrogate(uint);
  // static ushort lowSurrogate(uint);
  /// TODO: static ushort lowSurrogate(uint);
  // static QChar::Category category(uint);
  /// TODO: static QChar::Category category(uint);
  // static QChar::Direction direction(uint);
  /// TODO: static QChar::Direction direction(uint);
  // static QChar::JoiningType joiningType(uint);
  /// TODO: static QChar::JoiningType joiningType(uint);
  // static QChar::Joining joining(uint);
  /// TODO: static QChar::Joining joining(uint);
  // static unsigned char combiningClass(uint);
  /// TODO: static unsigned char combiningClass(uint);
  // static uint mirroredChar(uint);
  /// TODO: static uint mirroredChar(uint);
  // static bool hasMirrored(uint);
  /// TODO: static bool hasMirrored(uint);
  // static QString decomposition(uint);
  /// TODO: static QString decomposition(uint);
  // static QChar::Decomposition decompositionTag(uint);
  /// TODO: static QChar::Decomposition decompositionTag(uint);
  // static int digitValue(uint);
  /// TODO: static int digitValue(uint);
  // static uint toLower(uint);
  /// TODO: static uint toLower(uint);
  // static uint toUpper(uint);
  /// TODO: static uint toUpper(uint);
  // static uint toTitleCase(uint);
  /// TODO: static uint toTitleCase(uint);
  // static uint toCaseFolded(uint);
  /// TODO: static uint toCaseFolded(uint);
  // static QChar::Script script(uint);
  /// TODO: static QChar::Script script(uint);
  // static QChar::UnicodeVersion unicodeVersion(uint);
  /// TODO: static QChar::UnicodeVersion unicodeVersion(uint);
  // static QChar::UnicodeVersion currentUnicodeVersion();
  gonk::bind::static_member_function<QChar, QChar::UnicodeVersion, &QChar::currentUnicodeVersion>(char_, "currentUnicodeVersion").create();
  // static bool isPrint(uint);
  /// TODO: static bool isPrint(uint);
  // static bool isSpace(uint);
  /// TODO: static bool isSpace(uint);
  // static bool isMark(uint);
  /// TODO: static bool isMark(uint);
  // static bool isPunct(uint);
  /// TODO: static bool isPunct(uint);
  // static bool isSymbol(uint);
  /// TODO: static bool isSymbol(uint);
  // static bool isLetter(uint);
  /// TODO: static bool isLetter(uint);
  // static bool isNumber(uint);
  /// TODO: static bool isNumber(uint);
  // static bool isLetterOrNumber(uint);
  /// TODO: static bool isLetterOrNumber(uint);
  // static bool isDigit(uint);
  /// TODO: static bool isDigit(uint);
  // static bool isLower(uint);
  /// TODO: static bool isLower(uint);
  // static bool isUpper(uint);
  /// TODO: static bool isUpper(uint);
  // static bool isTitleCase(uint);
  /// TODO: static bool isTitleCase(uint);
}


void register_char__file(script::Namespace ns)
{
  using namespace script;


  register_latin1_char_class(ns);
  register_char__class(ns);

  // bool operator==(QChar, QChar);
  gonk::bind::op_eq<QChar, QChar>(ns);
  // bool operator<(QChar, QChar);
  gonk::bind::op_less<QChar, QChar>(ns);
  // bool operator!=(QChar, QChar);
  gonk::bind::op_neq<QChar, QChar>(ns);
  // bool operator>=(QChar, QChar);
  gonk::bind::op_geq<QChar, QChar>(ns);
  // bool operator>(QChar, QChar);
  gonk::bind::op_greater<QChar, QChar>(ns);
  // bool operator<=(QChar, QChar);
  gonk::bind::op_leq<QChar, QChar>(ns);
  // bool operator==(QChar, std::nullptr_t);
  /// TODO: bool operator==(QChar, std::nullptr_t);
  // bool operator<(QChar, std::nullptr_t);
  /// TODO: bool operator<(QChar, std::nullptr_t);
  // bool operator==(std::nullptr_t, QChar);
  /// TODO: bool operator==(std::nullptr_t, QChar);
  // bool operator<(std::nullptr_t, QChar);
  /// TODO: bool operator<(std::nullptr_t, QChar);
  // bool operator!=(QChar, std::nullptr_t);
  /// TODO: bool operator!=(QChar, std::nullptr_t);
  // bool operator>=(QChar, std::nullptr_t);
  /// TODO: bool operator>=(QChar, std::nullptr_t);
  // bool operator>(QChar, std::nullptr_t);
  /// TODO: bool operator>(QChar, std::nullptr_t);
  // bool operator<=(QChar, std::nullptr_t);
  /// TODO: bool operator<=(QChar, std::nullptr_t);
  // bool operator!=(std::nullptr_t, QChar);
  /// TODO: bool operator!=(std::nullptr_t, QChar);
  // bool operator>=(std::nullptr_t, QChar);
  /// TODO: bool operator>=(std::nullptr_t, QChar);
  // bool operator>(std::nullptr_t, QChar);
  /// TODO: bool operator>(std::nullptr_t, QChar);
  // bool operator<=(std::nullptr_t, QChar);
  /// TODO: bool operator<=(std::nullptr_t, QChar);
  // QDataStream& operator<<(QDataStream&, QChar);
  /// TODO: QDataStream& operator<<(QDataStream&, QChar);
  // QDataStream& operator>>(QDataStream&, QChar&);
  /// TODO: QDataStream& operator>>(QDataStream&, QChar&);
}
