// Copyright (C) 2020 Vincent Chambrin
// This file is part of the 'gonk' project
// For conditions of distribution and use, see copyright notice in LICENSE

// Warning: This file was generated by metagonk, all modifications will be lost. //

#ifndef GONK_QT_CORE_DEFS_H
#define GONK_QT_CORE_DEFS_H

#if (defined(WIN32) || defined(_WIN32))
#if defined(GONK_QT_CORE_COMPILE_LIBRARY)
#  define GONK_QT_CORE_API __declspec(dllexport)
#else
#  define GONK_QT_CORE_API __declspec(dllimport)
#endif
#else
#define GONK_QT_CORE_API
#endif

namespace gonk
{

namespace qt_core
{

} // namespace qt_core

} // namespace gonk

#endif // GONK_QT_CORE_DEFS_H
