// Copyright (C) 2020 Vincent Chambrin
// This file is part of the 'gonk' project
// For conditions of distribution and use, see copyright notice in LICENSE

// Warning: This file was generated by metagonk, all modifications will be lost. //

#ifndef GONK_QT_CORE_H
#define GONK_QT_CORE_H

#include "qt-core-defs.h"

#include "gonk/plugin.h"

extern "C"
{

  GONK_QT_CORE_API gonk::Plugin* gonk_qt_core_module();

} // extern "C"

#endif // GONK_QT_CORE_H
